### ISSUE TITLE
Store in Module aufteilen

### ISSUE THREAD

**Issue by fdaugs** [th-koeln/open-product-evaluation-server-admin#10]
Ich würde euch empfehlen den Store, gemäß den Entitäten in einzelne Modue aufzuteilen.

Docs: https://vuex.vuejs.org/guide/modules.html

**Comment by slemke** [comment]
Wird auch gemacht aktuell werden überall die Getter, Setter, ... usw implementiert. Daraufhin ersetzen wir das ganze mit einzelnen Modulen, dort wird dann auch deutlich wo wir die einzelnen Methoden zuordnen wollen.
