### ISSUE TITLE
Questions bei neuer Survey

### ISSUE THREAD

**Issue by fdaugs** [th-koeln/open-product-evaluation-server-admin#25]
Wenn man bei einer neuen Survey die erste Frage anlegt, wird diese erst angezeigt, sobald man die Seite neu lädt. Ähnlich ist es beim löschen von Fragen. Die letzte Frage wird (visuell) erst gelöscht, wenn die Seite neu geladen wird.

**Comment by slemke** [comment]
https://github.com/th-koeln/open-product-evaluation-server/issues/150
